
caasApiUrl: "http://xxxx/api/v1"
sslEnabled: true
proxyEnabled: false
proxyHost: "your http proxy host"
proxyPort: 3182
appKey: "your application key"
appSecret: "your application secret"
signEnabled: true
